import Head from "next/head";
import FooterAll from "../../components/footer";
import Link from "next/link";
import Image from "next/image";
import me from "../../public/images/pfp.jpeg";
import cake from "../../public/images/cake.jpg";
import shrimp from "../../public/images/shrimp.jpg";
import tree from "../../public/images/tree.jpg";
import unami from "../../public/images/unami.jpg";
import prettypic from "../../public/images/prettypic.jpg";
import snow from "../../public/images/snowphoto.jpg";
import downArrow from "../../public/images/downArrow.png";
import friends from "../../public/images/friends.jpg";
import skate from "../../public/images/skate.jpg";
import wecode from "../../public/images/wecode.jpg";
import MobileNav from "../../components/sideNavBar";
import HomeImages from "../../components/homeImage";
import React, { useState, useEffect } from "react";
import RotatingText from "@/components/rotate";

export default function Home() {
  return (
    <>
      <Head>
        <title>Maggie's Website</title>
        {/* <link rel="icon" href="../public/images/lemon.png" /> */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div id="top" className="lg:h-screen">
          <MobileNav />
          <div className="flex flex-col items-center justify-center h-full">
            <h1 className="title-name font-bold text-light-purp-text">
              <i>Hello</i>, I am{" "}
              <strong className="text-light-purp-text">Maggie</strong> 🍡
            </h1>
            <div className="title-sub flex flex-row ">
              <p className="pr-2">I&apos;m</p> <RotatingText></RotatingText>
            </div>
          </div>
          <div>
            {/* <div className="mx-3">
              <Image className="" src={me} width={300} />
            </div> */}
            <div className="about-me lg:text-left lg:w-1/2 flex flex-col text-center lg:mt-20 lg:ml-40">
              <div className="w-5/6 mx-auto p-2"></div>
            </div>
          </div>
          {/* <Image className="mx-auto" src={downArrow} /> */}
        </div>
        <div className="current mx-auto lg:p-10 lg:pb-20 lg:text-xl">
          <div className="mx-auto ">
            <h2 className="text-center text-xl">
              I like to do almost everything
            </h2>
            <HomeImages
              img={prettypic}
              img2={tree}
              img3={snow}
              altmessage={"picture of cornell"}
              altmessage2={"picture of tree"}
              altmessage3={"picture of snow"}
              title={"I love taking pictures of outdoors"}
            />
          </div>
        </div>
        <div>
          <h2>About me!</h2>
          <p>
            I&apos;m currently a junior majoring in Information Science with a
            concentration in Interactive Technology and a minor in Computer
            Science at Cornell University. I have a lot of interest in a variety
            of things, and I&apos;m constantly exploring new interests. I&apos;m
            passionate about social impact and developmental psychology. I&apos;m
            also interested in ML/AI while also dabbling in Front-end Design.
            This website will be mainly used for my interests and my portfolio.
          </p>
          <p className="coffee lg:pt-20 lg:pb-3 lg:text-sm">
                  <Link
                    href="https://calendly.com/mchen892/bobatalks"
                    target="_blank"
                  >
                    <span className="hover:underline">
                      Book a coffee chat with me ☕️
                    </span>
                  </Link>
                </p>
          <Image src={me}></Image>
        </div>

        <div>
          <h2>Experience</h2>
          <h3>Incoming Fullstack Developer @ Verizon</h3>
          <h3>Software Engineer @ Verizon</h3>
          <h3>Website Application Developer @ Factor Earth</h3>
          <h3>IBM Accelerate Software Track @ Verizon</h3>

          <h2>Activities</h2>
          <h3>Engineering For Sustainability World</h3>
          <h3>Cornell Rubber Ducky Club</h3>
        </div>

        {/* <div className="me lg:flex lg:flex-row lg:p-10 lg:pb-20 lg:text-xl">
          <div className="lg:ml-40 lg:w-1/2">
            <p>A Little About Me--</p>
            <ul className="p-5">
              <li>💃Favorite Activity To Do: Go to concerts</li>
              <li>🎵 I like to play to the piano</li>
              <li>🎨 I like to do digital art</li>
              <li>💻 Love Genshin Impact</li>
              <li>🍜Favorite Food is Ramen</li>
            </ul>
          </div>

          
          <iframe
            className=""
            src="https://open.spotify.com/embed/playlist/42e1NHVS6gTz87AC9NexwJ?utm_source=generator"
            width="100%"
            height="352"
            allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
            loading="lazy"
          ></iframe>
        </div> */}
        {/* <div className=""> */}
        {/* <p className="text-center text-lg">Other Ways that I exist </p> */}

        {/* <HomeImages
            img={prettypic}
            img2={tree}
            img3={snow}
            altmessage={"picture of cornell"}
            altmessage2={"picture of tree"}
            altmessage3={"picture of snow"}
            title={"I love taking pictures of outdoors"}
          />
          <div className="">
            <HomeImages
              img={cake}
              img2={unami}
              img3={shrimp}
              altmessage={"picture of cornell"}
              altmessage2={"picture of tree"}
              altmessage3={"picture of snow"}
              title={"Eating good food"}
            />
          </div>
          <div className="">
            <HomeImages
              img={skate}
              img2={friends}
              img3={wecode}
              altmessage={"picture of cornell"}
              altmessage2={"picture of tree"}
              altmessage3={"picture of snow"}
              title={"Hanging with friends"}
            />
          </div>
        </div> */}
        <FooterAll />
      </main>
    </>
  );
}
