import Head from "next/head";
import MobileNav from "../../components/sideNavBar";
import FooterAll from "../../components/footer";
import Link from "next/link";
import Image from "next/image";
import JournalTemplate from "../../components/journalTemp";
// import website from '../public/website.png'

export default function Journal() {
  return (
    <>
      <Head>
        <title>Maggie's Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen">
          <MobileNav />
          <h1>Journal</h1>
          <JournalTemplate date="March 2024" info={[""]} />
          <JournalTemplate
            date="Febuary 2024"
            info={[
              "Received a return offer for Verizon",
              "Went to Cancun for Feb Break!",
            ]}
          />
          <JournalTemplate
            date="January 2024"
            info={[
              "Second semester of junior year",
              "Finished my sprinternship at Verizon & learned lots of new skills",
            ]}
          />
          <JournalTemplate
            date="August 2023"
            info={[
              "Finished Codepath course",
              "Finished IBM Accelerator",
              "Started Junior year",
            ]}
          />
          <JournalTemplate date="July 2023" info={["Went to Seattle"]} />
          <JournalTemplate
            date="June 2023"
            info={[
              "Starting my first course with IBM Accelerator: software track",
              "Taking a CodePath Course",
              "Doing React Native with Dandilyonn",
            ]}
          />
          <JournalTemplate
            date="May 2023"
            info={[
              "Started my website redesign",
              "Last Day of Classes",
              "Started my 2nd summer interning at Factor Earth",
            ]}
          />
        </div>
        <FooterAll />
      </main>
    </>
  );
}
