import Head from "next/head";
import MobileNav from "../../components/sideNavBar";
import FooterAll from "../../components/footer";
import ProjectTemp from "../../components/projectTemp";
import esw from "../../public/images/esw.png";
import cssa from "../../public/images/cssa_website.png";
import arduino from "../../public/images/arduino.png";
import website from "../../public/images/personal.jpg";
import bobatalk from "public/images/bobatalks.png";
import hungryline from "public/images/hungryline.png";

export default function Home() {
  return (
        <>
          <Head>
            <title>Maggie's Website</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <MobileNav />
            <section className="text-center mt-2 pt-5">
            <h2 className="text-3xl text-center font-semibold p-5 mb-8">Projects</h2>

              <div className="project-view">
                <ProjectTemp link='https://www.maggiechen.org/'img={website} altmessage="Personal website image" title="Personal Website" caption="Used NextJS, Tailwind, HTML, and CSS" />
                <ProjectTemp img={esw} altmessage="Esw website image" title="Engineer's For Sustainability Website" caption="Used Plotly Dash, Bootstrap components, CSS, Figma for the website. Used pandas for fumehood automations." />
                <ProjectTemp link='https://github.com/mchen892/led-clock'img={arduino} altmessage="Arduino LED Clock" title="Arduino LED Clock" caption="Used Arduino to create this" />
                <ProjectTemp link='https://survival-guide.netlify.app/ 'img={bobatalk} altmessage="BobaTalk website image" title="BobaTalk's College Survival Website" caption="Used React and CSS" />
                <ProjectTemp link='https://github.com/mchen892/hungry-line' img={hungryline} altmessage="Hungry Line app image" title="Hungry Line App" caption="Used React Native, Expo, and Firebase" />
              </div>
            </section>
            <FooterAll />
          </main>
        </>
      );
  }