import Head from 'next/head';
import MobileNav from "../../components/sideNavBar";
import FooterAll from "../../components/footer";
import esw from '../../public/images/esw.png';
import cssa from '../../public/images/cssa_website.png';
import arduino from '../../public/images/arduino.png';
import website from '../../public/images/personal.jpg';
import ProjectTemp from '../../components/projectTemp';

export default function Home() {
  return (
    <>
      <Head>
        <title>Maggie&apos;s Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MobileNav />
        <h2 className='text-xl text-center mt-2 pt-5'>Projects I&apos;ve Done</h2>


        <div className='flex flex-row mb-2 p-5 flex-wrap justify-center '>
          <ProjectTemp
            img={website}
            altmessage={"image of the website"}
            title={"Personal Website"}
            caption={"Used react, tailwind, html, and css "}
          />

          <ProjectTemp
            img={esw}
            altmessage={"Engineer's For Sustainability Website"}
            title={"Engineer's For Sustainability Website"}
            caption={"Used Plotly Dash, Bootstrap components, css, and"}
          />

          <ProjectTemp
            img={cssa}
            altmessage={"image of the website"}
            title={"CCornell Chinese Scholars Association Website"}
            caption={"Used html, css, and JS to create this website"}
          />

          <ProjectTemp
            img={arduino}
            altmessage={"image of the website"}
            title={"Arduino LED Clock"}
            caption={"Used Arduino to create this "}
          />

          <ProjectTemp
            img={esw}
            altmessage={"BobaTalk's College Survival Website"}
            title={"BobaTalk's College Survival Website"}
            caption={"Used react, tailwind, html, and css "}
          />

          <ProjectTemp
            img={esw}
            altmessage={"Discord trading analyzing bot"}
            title={"Discord trading analyzing bot"}
            caption={"Used python, yahoo finaces, discord"}
          />

          <ProjectTemp
            img={esw}
            altmessage={"Queue app"}
            title={"Hungry Line app"}
            caption={"Used react native, firebase"}
          />
        </div>
        <FooterAll />
      </main>
    </>
  );
}
