import Head from 'next/head'
import MobileNav from "../../components/sideNavBar";
import FooterAll from "../../components/footer";import Link from 'next/link'
import Image from 'next/image'
import birb from '../../public/images/birb.jpg'
import birb2 from '../../public/images/birb2.jpg'
import birb3 from '../../public/images/birb3.jpg'
import cherry from '../../public/images/cherry.jpg'
import staw from '../../public/images/staw.jpg'
import bear from '../../public/images/bear.jpg'

export default function Home() {
    return (
        <>
            <Head>
                <title>Maggie&apos;s Website</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
               <MobileNav />
                <h2 className='text-center mt-24 text-3xl'>Stickers</h2>
                <div className="flex flex-col lg:flex-row lg:flex-wrap lg:m-28">

                    <Link className='lg:w-1/3 mx-auto px-7 pb-16' href="https://www.redbubble.com/i/sticker/Bear-by-cherrylemoncat/83822568.EJUG5" target="_blank">
                        <Image src={bear} alt='image of bear'/></Link>

                    <Link className='lg:w-1/3 mx-auto px-7 pb-16' href="https://www.redbubble.com/i/sticker/Cherry-by-cherrylemoncat/83824496.EJUG5" target="_blank">
                        <Image src={cherry} alt='image of cherry'/></Link>

                    <Link className='lg:w-1/3 mx-auto px-7' href="https://www.redbubble.com/i/sticker/Frog-bird-with-wings-by-cherrylemoncat/83889096.EJUG5"
                        target="_blank"><Image src={birb} alt='image of bird'/></Link>

                    <Link className='lg:w-1/3 mx-auto px-7' href="https://www.redbubble.com/i/sticker/Bird-in-frog-costume-by-cherrylemoncat/83889180.EJUG5"
                        target="_blank"><Image src={birb2} alt='image of bird'/></Link>

                    <Link className='lg:w-1/3 mx-auto px-7' href="https://www.redbubble.com/i/sticker/Bird-in-frog-costume-by-cherrylemoncat/83889253.EJUG5"
                        target="_blank"><Image src={birb3} alt='image of bird'/></Link>

                    <Link className='lg:w-1/3 mx-auto px-7' href="https://www.redbubble.com/i/sticker/Strawberry-milk-by-cherrylemoncat/85399973.EJUG5"
                        target="_blank"><Image src={staw} alt='image of stawberry'/></Link>

                </div>
                <FooterAll />
            </main>
        </>
    )
}
