import Head from 'next/head'
import MobileNav from "../components/sideNavBar";
import FooterAll from "../components/footer";
import Link from 'next/link'
import Image from 'next/image'
// import website from '../public/website.png'


export default function Home() {
    return (
        <>
            <Head>
                <title>Maggie's Website</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className='h-screen'>
                <MobileNav />
                    <div className='lg:ml-80 lg:mt-32 p-2'>
                        <h2 className=' text-xl p-2'>May 2023</h2>
                        <ul className="list-disc ml-10">
                            <li>Redesigning my website</li>
                            <li>Last Day of Classes</li>
                            <li>Started my 2nd summer interning at Factor Earth</li>
                        </ul>
                        {/* <Image src={website} /> */}
                        <h2 className=' text-xl p-2'>June</h2>
                        <ul className="list-disc ml-10">
                            <li>Starting my first course with IBM Accelerator: software track</li>
                            <li>Taking a CodePath Course</li>
                            <li>Doing React Native with Dandilyonn</li>
                        </ul>
                    </div>
                </div>
                <FooterAll />
            </main>
        </>
    )
}