import Head from 'next/head'
import FooterAll from "../components/footer";
import Link from 'next/link'
import Image from 'next/image'
import me from '../public/me.png'
import cake from '../public/cake.jpg'
import shrimp from '../public/shrimp.jpg'
import tree from '../public/tree.jpg'
import unami from '../public/unami.jpg'
import soother from '../public/soother.jpg'
import prettypic from '../public/prettypic.jpg'
import snow from '../public/snowphoto.jpg'
import downArrow from '../public/downArrow.png'
import friends from '../public/friends.jpg'
import skate from '../public/skate.jpg'
import wecode from '../public/wecode.jpg'
import MobileNav from '../components/sideNavBar';
import HomeImages from '@/components/HomeImage';


export default function Home() {
  return (
    <>
      <Head>
        <title>Maggie's Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div id='top' className='lg:h-screen'>
          <MobileNav />
          <div className='flex flex-col text-center lg:flex lg:flex-row-reverse '>
            <div className='mx-auto mt-100'>
              <Image className='sm:mx-auto mt-14 mr-7' src={me} />
            </div>
            <div className='about-me lg:text-left lg:w-1/2 flex flex-col text-center lg:mt-20 lg:ml-40'>
              <div className='w-5/6 mx-auto p-2'>
                <p className='text-3xl text-center'>Hi! I’m <strong>Maggie Chen</strong> 🍡</p>
                <p className='pt-2 text-start'>
                  I’m currently a rising junior majoring in Information Science with a concentration in Interactive Technology and a minor in Computer Science at Cornell University.
                </p>
                <p className='lg:pt-2 text-start'>
                  I have a lot of interest in a variety of things, and I’m constantly exploring new interests.
                </p>
                <p className='lg:pt-2 text-start'>
                  I'm passionate about social impact and developmental psychology. I’m also interested in ML/AI while also dabbling in Front-end Design.
                </p>
                <p className='lg:pt-2 text-start'>
                  This website will be mainly used for my interests and my portfolio.
                </p>
                <p className='lg:mt-10 text-start'>
                  I'm <strong>currently</strong> looking for a <strong>2024 summer internship</strong> in Software Development.
                </p>

                <p className='coffee lg:pt-20 lg:pb-3 lg:text-sm'>
                  <Link href='https://calendly.com/mchen892/bobatalks' target='_blank'>
                    <span className="hover:underline">Book a coffee chat with me ☕️</span>
                  </Link>
                </p>
              </div>
            </div>
          </div>
          <Image className='mx-auto' src={downArrow} />
        </div>
        <div className='current mx-auto lg:p-10 lg:pb-20 lg:text-xl'>
          <div className='mx-auto '>
            <p className='pt-5 pb-5 text-center'>What Am I Doing Currently? </p>
            <div className='lg:flex lg:flex-row lg:justify-between'>
              <ul className='mx-auto lg:ml-52 list-disc lg:w-1/2'>
                <li>
                  Interning at Factor Earth (summer 2023)
                </li>
                <li>
                  Doing a program with IBM & CodePath (summer 2023)
                </li>
                <li>
                  Learning React
                </li>
                <li>
                  Learning React Native
                </li>
              </ul>
              <ul className='mx-auto lg:ml-52 list-disc lg:w-1/2'>
                <li>
                  Working on a personal project
                </li>
                <li>
                  Co-president for Cornell Rubber Ducky Coding Club
                </li>
                {/* Add more activities here */}
              </ul>
            </div>
          </div>
        </div>
        <div className='me lg:flex lg:flex-row lg:p-10 lg:pb-20 lg:text-xl'>
          <div className='lg:ml-40 lg:w-1/2'>
            <p>A Little About Me--</p>
            <ul className='p-5'>
              <li>
                💃Favorite Activity To Do: Go to concerts
              </li>
              <li>
                🎵 I like to play to the piano
              </li>
              <li>
                🎨 I like to do digital art
              </li>
              <li>
                💻 Love Genshin Impact
              </li>
              <li>
                🍜Favorite Food is Ramen
              </li>
            </ul>
          </div>
          <iframe className='' src="https://open.spotify.com/embed/playlist/42e1NHVS6gTz87AC9NexwJ?utm_source=generator"
            width="100%" height="352" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
            loading="lazy"></iframe>
        </div>
        <div className="">
          <p className='text-center text-lg'>Other Ways that I exist </p>
          
          {/* <div className='flex flex-col'>
            <div className='mx-auto'> */}
              <HomeImages
                img={prettypic}
                img2={tree}
                img3={snow}
                altmessage={"picture of cornell"}
                altmessage2={"picture of tree"}
                altmessage3={"picture of snow"}
                title={"I love taking pictures of outdoors"}
              />
            {/* </div> */}
            <div className=''>
              <HomeImages
                img={cake}
                img2={unami}
                img3={shrimp}
                altmessage={"picture of cornell"}
                altmessage2={"picture of tree"}
                altmessage3={"picture of snow"}
                title={"Eating good food"}
              />
            </div>
            <div className=''>
              <HomeImages
                img={skate}
                img2={friends}
                img3={wecode}
                altmessage={"picture of cornell"}
                altmessage2={"picture of tree"}
                altmessage3={"picture of snow"}
                title={"Hanging with friends"}
              />
            </div>

          {/* </div> */}
          {/* <div className='flex flex-col-reverse lg:flex-row'>
            <div className='flex flex-col lg:flex-row lg:p-2 lg:ml-40'>
              <Image className='mx-auto pt-3 pb-3 lg:p-5 lg:mx-0' src={prettypic} />
              <Image className='mx-auto pt-3 pb-3 lg:p-5 lg:mx-0' src={tree} />
              <Image className='mx-auto pt-3 pb-3 lg:p-5 lg:mx-0' src={snow} />
            </div> */}
          {/* <div className='mx-auto'>
              Taking pretty photos
            </div> */}
          {/* </div> */}
          {/* <div className='flex flex-col-reverse lg:flex-row'>
            <div className='flex flex-col lg:flex-row lg:p-2 lg:ml-40'>
              <Image className='mx-auto pt-3 pb-3 lg:p-5 lg:mx-0' src={unami} />
              <Image className='mx-auto pt-3 pb-3 lg:p-5 lg:mx-0' src={cake} />
              <Image className='mx-auto pt-3 pb-3 lg:p-5 lg:mx-0' src={shrimp} />
            </div>
            <div className='mx-auto'>
              Foodie
            </div>
          </div> */}
          {/* <div className='flex flex-col-reverse lg:flex-row'>
            <div className='flex flex-col lg:flex-row lg:p-2 lg:ml-40'>
              <Image className='mx-auto pt-3 pb-3 lg:p-5 lg:mx-0' src={friends} />
              <Image className='mx-auto pt-3 pb-3 lg:p-5 lg:mx-0' src={skate} />
              <Image className='mx-auto pt-3 pb-3 lg:p-5 lg:mx-0' src={wecode} />
            </div>
            <div className='mx-auto'>
              Hanging with friends
            </div>
          </div> */}
        </div>
        <FooterAll />
      </main >
    </>
  )
}